<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="0.075" timestamp="2025-05-22T15:20:17.701976+08:00" hostname="Lenovo-Rory"><testcase classname="testcase.test_api.TestAPI" name="test_api[base_info0-testcase0]" time="0.006"><failure message="requests.exceptions.InvalidSchema: No connection adapters were found for '&lt;http://127.0.0.1:5000&gt;/test'">self = &lt;testcase.test_api.TestAPI object at 0x000001FACD3CC050&gt;
base_info = {'api_name': '简单API测试', 'header': {'Content-Type': 'application/json'}, 'method': 'GET', 'url': '/test'}
testcase = {'case_name': '正常请求', 'request_params': {}, 'validation': {'message': 'Success', 'status_code': 200}}

    @allure.story(next(c_id) + "测试接口")
    @pytest.mark.parametrize('base_info,testcase', get_testcase_yaml('./data/test_data.yaml'))
    def test_api(self, base_info, testcase):
        allure.dynamic.title(testcase['case_name'])
&gt;       RequestBase().specification_yaml(base_info, testcase)

testcase\test_api.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
base\apiutil.py:20: in specification_yaml
    return self.run.run_main(
common\sendrequest.py:37: in run_main
    response = session.request(
.venv\Lib\site-packages\requests\sessions.py:589: in request
    resp = self.send(prep, **send_kwargs)
.venv\Lib\site-packages\requests\sessions.py:697: in send
    adapter = self.get_adapter(url=request.url)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;requests.sessions.Session object at 0x000001FACD36B8C0&gt;
url = '&lt;http://127.0.0.1:5000&gt;/test'

    def get_adapter(self, url):
        """
        Returns the appropriate connection adapter for the given URL.
    
        :rtype: requests.adapters.BaseAdapter
        """
        for prefix, adapter in self.adapters.items():
            if url.lower().startswith(prefix.lower()):
                return adapter
    
        # Nothing matches :-/
&gt;       raise InvalidSchema(f"No connection adapters were found for {url!r}")
E       requests.exceptions.InvalidSchema: No connection adapters were found for '&lt;http://127.0.0.1:5000&gt;/test'

.venv\Lib\site-packages\requests\sessions.py:792: InvalidSchema</failure></testcase></testsuite></testsuites>